[#XX] Update aio to v0.30.0
nspcc-dev/neofs-aio pull request #31
Opened 2022-07-26 10:10 UTC by KirillovDenis

Signed-off-by: Denis Kirillov <denis@nspcc.ru>

2022-07-26 10:50 UTC, masterSplinter01 submitted a review, later dismissed

2022-07-26 13:08 UTC, alexvanin requested changes
Please check `docker-compose.cross.yaml` file. It rewrites endpoints in `environment` section to be compatible with docker networking. So you have to update values there as well:
1) storage node rpc endpoint
2) inner ring rpc endpoint
3) add rpc endpoint to http gateway

2022-07-26 13:10 UTC, alexvanin commented
We can discuss removing of `docker-compose.yaml` in favor of `docker-compose.cross.yaml` (maybe in the context of #17). Don't think @realloc will like it, though.

2022-07-26 13:16 UTC, realloc commented
Think, we can move to the `cross` version completely if we clearly describe in README that `neofs-aio` must not be used to set up one-node NeoFS installations and should be used for app development like a simplified version of `nepfs-dev-env`.

2022-07-27 10:38 UTC, alexvanin approved these changes

2022-07-27 10:38 UTC, merged